/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lar.telas;

import java.awt.Color;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import lar.entidade.ResourceWeb;
import lar.jena.QueriesSparql;

/**
 *
 * @author Renato
 */
public class FrmDisease extends javax.swing.JFrame {

    private ResourceWeb disease;

    /**
     * @return the disease
     */
    public ResourceWeb getDisease() {
        return disease;
    }

    public void setDisease(ResourceWeb disease) {
        this.disease = disease;
    }

    public FrmDisease() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSelectedDisease = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbUrlImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        peImage = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPossibleDrugs = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaAboutDrug = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstActiveIngredient = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        lbHasOrNoDrugs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sadis - Informações sobre a Doença");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbSelectedDisease.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbSelectedDisease.setForeground(new java.awt.Color(12, 10, 200));
        lbSelectedDisease.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSelectedDisease.setText("Detalhes da Doença");
        lbSelectedDisease.setAlignmentY(0.0F);
        jPanel1.add(lbSelectedDisease, java.awt.BorderLayout.CENTER);

        jLabel8.setText("Fonte de Dados: http://dbpedia.org, http://wikidata.org");

        lbUrlImage.setText("Fonte da Imagen: ");

        jScrollPane1.setViewportView(peImage);

        lstPossibleDrugs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPossibleDrugsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstPossibleDrugs);

        jLabel1.setText("Possíveis Drogas Usadas no Tratamento");

        txaAboutDrug.setColumns(20);
        txaAboutDrug.setRows(5);
        jScrollPane3.setViewportView(txaAboutDrug);

        jLabel2.setText("Sobre a Droga");

        jScrollPane4.setViewportView(lstActiveIngredient);

        jLabel3.setText("Ingrediente Ativo em");

        lbHasOrNoDrugs.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbHasOrNoDrugs.setForeground(new java.awt.Color(0, 153, 204));
        lbHasOrNoDrugs.setText("(Selecione uma droga)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbUrlImage)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHasOrNoDrugs)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbHasOrNoDrugs)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUrlImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("lar.telas.FrmDisease.formWindowOpened()" + disease.getDrugs());

        this.lbSelectedDisease.setText(this.disease.getLabel());
        this.lbUrlImage.setText(this.lbUrlImage.getText() + disease.getImage());

        if (disease.getDrugs().size() > 0) {
            this.lstPossibleDrugs.setModel(disease.getDrugs());
        } else {
            lbHasOrNoDrugs.setText("(Nada encontrado!)");
        }

//        if (!disease.getImage().isEmpty()) {
//            try {
//                URL urlImg = new URL(disease.getImage());
//                BufferedImage image = ImageIO.read(urlImg);
//                while (image.getImageLoadStatus() == MediaTracker.LOADING);
//                File fileImage = new File("diseaseImage.jpg");
//                ImageIO.write(image, "jpg", fileImage);
//                System.out.println("lar.telas.FrmDisease.formWindowOpened(), imgIcon > " + fileImage);
//                this.lbDiseaseImage.setIcon((Icon) fileImage);
//                peImage.setPage(disease.getImage());
//                peImage.setPage("https://www.wikidata.org/wiki/Q183130#/media/File:Gastritis_erosiva.2278.jpg");
//                peImage.setPage(disease.getImage());
//            } catch (MalformedURLException ex) {
//                Logger.getLogger(FrmDisease.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(FrmDisease.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//            System.out.println("lar.telas.FrmDisease.formWindowOpened(), NÃO VEIO IMAGE");
//        }
    }//GEN-LAST:event_formWindowOpened

    private void lstPossibleDrugsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPossibleDrugsMouseClicked
        Object o = (Object) lstPossibleDrugs.getSelectedValue();
        ResourceWeb selectedDrug = (ResourceWeb) o;
        ResourceWeb rsw = QueriesSparql.getDescriptonAndAlsoKnowAsFromWikiDataByDrug(selectedDrug);

        txaAboutDrug.setText(rsw.getComment());
        lstActiveIngredient.setModel(rsw.getActiveIngredientIn());
    }//GEN-LAST:event_lstPossibleDrugsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDisease().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbHasOrNoDrugs;
    private javax.swing.JLabel lbSelectedDisease;
    private javax.swing.JLabel lbUrlImage;
    private javax.swing.JList<String> lstActiveIngredient;
    private javax.swing.JList<String> lstPossibleDrugs;
    private javax.swing.JEditorPane peImage;
    private javax.swing.JTextArea txaAboutDrug;
    // End of variables declaration//GEN-END:variables
}
