/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lar.telas;

import java.io.File;
import javax.swing.JLabel;
import lar.negocio.TemplateLinkSpec;

/**
 *
 * @author renato
 */
public class FrmResolucaoIdentidade extends javax.swing.JFrame {

    /**
     * Creates new form FrmResolucaoIdentidade
     */
    public FrmResolucaoIdentidade() {
        initComponents();
        this.carregaCombos();
        this.carregaComboArquivosTemporarios();
    }
    
    private JLabel itemIniciaDeCombo = new JLabel("Chosse a File");
    
    public void carregaCombos() {
        File[] files = new File("/tmp").listFiles();
        this.cbDatasetFonte.addItem(itemIniciaDeCombo.getText());
        this.cbDatasetAlvo.addItem(itemIniciaDeCombo.getText());

        for (File file : files) {
            if (file.isFile() & file.getName().endsWith(".nt")) {
                this.cbDatasetFonte.addItem(file.getName());
                this.cbDatasetAlvo.addItem(file.getName());
            }
        }
    }

    public void carregaComboArquivosTemporarios() {
        File[] files = new File("/tmp").listFiles();
        this.cbEscolherArquivoEditar.addItem(itemIniciaDeCombo.getText());

        for (File file : files) {
            if (file.isFile() & file.getName().endsWith(".xml")) {
                this.cbEscolherArquivoEditar.addItem(file.getName());
            }
        }
    }
    
    
    /**
     
     Deverá ter uma combo para escolher quais atributos serão comparados para cadas para <fonte, alvo>
     * Um botão para adicionar cada comparação
     * 
     * Tipos de comparação básicas
     * Equality = retorna 0 se as string são iguai e 1 se não.
     * Date = distância em dias entre duas datas (formato 'YYYY-MM-DD') 
     * DateTime = distância em dias entre duas datas (formato xsd:datetime) 
     * Jaccard = Jaccard Coeficiente de similaridade.
     * Levenshtein distance  = retorna o valor da distância entre 0 e o tamanho da string
     */
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cbDatasetFonte = new javax.swing.JComboBox<>();
        cbDatasetAlvo = new javax.swing.JComboBox<>();
        btnFecharSemSalvar = new javax.swing.JButton();
        btnSalvarNoutroDiretorio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbEscolherArquivoEditar = new javax.swing.JComboBox<>();
        btnGerarAquivoSilk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLinkSpec = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cbPropriedade = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbTipoDeComparacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Dataset Source");

        jLabel2.setText("Dataset Target");

        btnSalvar.setText("Save");

        btnFecharSemSalvar.setText("Close without save");

        btnSalvarNoutroDiretorio.setText("Save in nother folder");

        jLabel3.setText("File to Edit");

        btnGerarAquivoSilk.setText("To Specify Semantic Links");
        btnGerarAquivoSilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarAquivoSilkActionPerformed(evt);
            }
        });

        txtAreaLinkSpec.setColumns(20);
        txtAreaLinkSpec.setRows(5);
        jScrollPane1.setViewportView(txtAreaLinkSpec);

        jLabel4.setText("Compare Property");

        btnAdd.setText("Add");

        jLabel5.setText("Type of Comparation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(cbDatasetFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(13, 13, 13))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cbDatasetAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSalvarNoutroDiretorio, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(btnFecharSemSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGerarAquivoSilk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbEscolherArquivoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbTipoDeComparacao, javax.swing.GroupLayout.Alignment.LEADING, 0, 177, Short.MAX_VALUE)
                                        .addComponent(cbPropriedade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd)))
                        .addGap(6, 6, 6))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFecharSemSalvar, btnSalvar, btnSalvarNoutroDiretorio});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDatasetFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDatasetAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoDeComparacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEscolherArquivoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnFecharSemSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarNoutroDiretorio)
                .addGap(39, 39, 39)
                .addComponent(btnGerarAquivoSilk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarAquivoSilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarAquivoSilkActionPerformed
        String t = TemplateLinkSpec.geraPrefixos();
        this.txtAreaLinkSpec.setText(t);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarAquivoSilkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmResolucaoIdentidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmResolucaoIdentidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmResolucaoIdentidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmResolucaoIdentidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmResolucaoIdentidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFecharSemSalvar;
    private javax.swing.JButton btnGerarAquivoSilk;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarNoutroDiretorio;
    private javax.swing.JComboBox<String> cbDatasetAlvo;
    private javax.swing.JComboBox<String> cbDatasetFonte;
    private javax.swing.JComboBox<String> cbEscolherArquivoEditar;
    private javax.swing.JComboBox<String> cbPropriedade;
    private javax.swing.JComboBox<String> cbTipoDeComparacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaLinkSpec;
    // End of variables declaration//GEN-END:variables
}
