/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lar.telas;

import java.awt.Color;
import javax.swing.DefaultListModel;
import lar.entidade.ResourceWeb;
import lar.jena.QueriesSparql;

/**
 *
 * @author Renato
 */
public class FrmSymptomsIntegration extends javax.swing.JFrame {

    /**
     * Creates new form FrmSymptomsIntegration
     */
    public FrmSymptomsIntegration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCountWikiSignals = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstWikiSignals = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDbpediaSymptoms = new javax.swing.JList<>();
        lblCountDbpediaSymptoms = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaSignalSymptom = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblCountWikiSymptoms = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstWikiSymptoms = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        lblCountDbpediaSymptoms1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstDbpediaSymptoms1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Wikidata Sinais");

        lblCountWikiSignals.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCountWikiSignals.setForeground(new java.awt.Color(0, 153, 204));
        lblCountWikiSignals.setText("(Selecione uma droga)");

        lstWikiSignals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstWikiSignalsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstWikiSignals);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 10, 200));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intregrar Sintomas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lstDbpediaSymptoms);

        lblCountDbpediaSymptoms.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCountDbpediaSymptoms.setForeground(new java.awt.Color(0, 153, 204));
        lblCountDbpediaSymptoms.setText("(Selecione uma droga)");

        jLabel3.setText("DBPedia Sintomas");

        txaSignalSymptom.setColumns(20);
        txaSignalSymptom.setLineWrap(true);
        txaSignalSymptom.setRows(5);
        txaSignalSymptom.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txaSignalSymptom);

        jLabel4.setText("Wikidata Sintomas");

        lblCountWikiSymptoms.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCountWikiSymptoms.setForeground(new java.awt.Color(0, 153, 204));
        lblCountWikiSymptoms.setText("(Selecione uma droga)");

        lstWikiSymptoms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstWikiSymptomsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lstWikiSymptoms);

        jLabel5.setText("DBPedia Sintomas");

        lblCountDbpediaSymptoms1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblCountDbpediaSymptoms1.setForeground(new java.awt.Color(0, 153, 204));
        lblCountDbpediaSymptoms1.setText("(Selecione uma droga)");

        jScrollPane5.setViewportView(lstDbpediaSymptoms1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCountWikiSignals)
                                .addComponent(jLabel1))
                            .addGap(151, 151, 151)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(lblCountWikiSymptoms)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblCountDbpediaSymptoms1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblCountDbpediaSymptoms)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountDbpediaSymptoms1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountWikiSignals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountWikiSymptoms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountDbpediaSymptoms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstWikiSignalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstWikiSignalsMouseClicked
        Object o = (Object) lstWikiSignals.getSelectedValue();
        ResourceWeb selectedDrug = (ResourceWeb) o;
        String rsw = QueriesSparql.getWikiComment(selectedDrug);

        System.out.println("lar.telas.FrmSymptomsIntegration.lstWikidataSymptomsMouseClicked(), rsw > " + rsw);

        if (!rsw.equals("")) {
            txaSignalSymptom.setText(rsw);
            txaSignalSymptom.setForeground(Color.BLACK);
            txaSignalSymptom.setBackground(Color.WHITE);
        }else{
            txaSignalSymptom.setText("Sem comentário!");
            txaSignalSymptom.setForeground(Color.red);
            txaSignalSymptom.setBackground(Color.PINK);
        }

    }//GEN-LAST:event_lstWikiSignalsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultListModel wikiSignals = QueriesSparql.getWikiSignals();
        lstWikiSignals.setModel(wikiSignals);
        lblCountWikiSignals.setText(wikiSignals.size() + " Sinais");

        DefaultListModel wikiSymptoms = QueriesSparql.getWikiSymptoms();
        lstWikiSymptoms.setModel(wikiSymptoms);
        lblCountWikiSymptoms.setText(wikiSymptoms.size() + " Sintomas");
        System.out.println(wikiSymptoms.size() + "lar.telas.FrmSymptomsIntegration.formWindowOpened(), size() > ");
    }//GEN-LAST:event_formWindowOpened

    private void lstWikiSymptomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstWikiSymptomsMouseClicked
        Object o = (Object) lstWikiSymptoms.getSelectedValue();
        ResourceWeb selectedDrug = (ResourceWeb) o;
        String rsw = QueriesSparql.getWikiComment(selectedDrug);

        System.out.println("lar.telas.FrmSymptomsIntegration.lstWikidataSymptomsMouseClicked(), rsw > " + rsw);

        if (!rsw.equals("")) {
            txaSignalSymptom.setText(rsw);
            txaSignalSymptom.setForeground(Color.BLACK);
            txaSignalSymptom.setBackground(Color.WHITE);
        }else{
            txaSignalSymptom.setText("Sem comentário!");
            txaSignalSymptom.setForeground(Color.red);
            txaSignalSymptom.setBackground(Color.PINK);
        }
    }//GEN-LAST:event_lstWikiSymptomsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSymptomsIntegration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSymptomsIntegration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSymptomsIntegration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSymptomsIntegration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSymptomsIntegration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCountDbpediaSymptoms;
    private javax.swing.JLabel lblCountDbpediaSymptoms1;
    private javax.swing.JLabel lblCountWikiSignals;
    private javax.swing.JLabel lblCountWikiSymptoms;
    private javax.swing.JList<String> lstDbpediaSymptoms;
    private javax.swing.JList<String> lstDbpediaSymptoms1;
    private javax.swing.JList<String> lstWikiSignals;
    private javax.swing.JList<String> lstWikiSymptoms;
    private javax.swing.JTextArea txaSignalSymptom;
    // End of variables declaration//GEN-END:variables
}
